"""Interactive CLI for generating Claude Code, Codex, and Pi dev containers."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, StrictUndefined, TemplateError


TOOL_NAME = "codex-claude-devcontainer-configurator"
CONFIG_VERSION = 4
DEVCONTAINER_DIRNAME = ".devcontainer"
ROOT_STATE_FILENAME = ".devcontainer-configurator.json"
MARKER_FILENAME = ".managed-file-hashes.json"
TEMPLATE_FINGERPRINT_KEY = "template_fingerprint"
LEGACY_MARKER_FILENAMES = [
    ".devcontainer-configurator-managed-file-hashes.json",
    ".codex-claude-devcontainer-configurator.json",
]
MANAGED_FILES = ["Dockerfile", "devcontainer.json", "init-firewall.sh"]
MASKED_FILE_PLACEHOLDER = ".empty-mask"

DEFAULT_MASKED_PATHS = [".jj", ".git"]
DEFAULT_READ_ONLY_PATHS = [".devcontainer"]
MASKED_SCAN_PATHS_KEY = "masked_scan_paths"
READ_ONLY_SCAN_PATHS_KEY = "read_only_scan_paths"
VENV_DIRNAME = ".venv"
PACKAGE_MANAGER_LOCK_FILENAMES = {
    "package-lock.json",
    "yarn.lock",
    "uv.lock",
}
WORKSPACE_SCAN_IGNORED_DIRS = {
    ".devcontainer",
    ".git",
    ".hg",
    ".jj",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "build",
    "dist",
    "node_modules",
    "venv",
}
DEFAULT_HOST_PORTS: list[int] = []
HOST_PORTS_ENV = "DEVCONTAINER_HOST_PORTS"
DEFAULT_GPU = {"mode": "none", "device": ""}
GPU_MODES = {"none", "device", "all"}
TEMPLATE_DIRECTORY = Path(__file__).with_name("templates")
DOCKERFILE_TEMPLATE_NAME = "Dockerfile.j2"
DEVCONTAINER_TEMPLATE_NAME = "devcontainer.json.j2"
FIREWALL_TEMPLATE_NAME = "init-firewall.sh.j2"
TEMPLATE_NAMES = [
    DOCKERFILE_TEMPLATE_NAME,
    DEVCONTAINER_TEMPLATE_NAME,
    FIREWALL_TEMPLATE_NAME,
]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Claude Code, Codex, and Pi .devcontainer directory."
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=Path.cwd(),
        help="Workspace where .devcontainer should be created. Defaults to the current directory.",
    )
    args = parser.parse_args(argv)

    try:
        return configure(args.workspace.resolve())
    except ValueError as exc:
        print(f"error: {exc}")
        return 1


def configure(workspace: Path) -> int:
    if not workspace.exists() or not workspace.is_dir():
        raise ValueError(f"{workspace} is not a directory")

    devcontainer_dir = workspace / DEVCONTAINER_DIRNAME
    root_state_path = workspace / ROOT_STATE_FILENAME
    marker_path = devcontainer_dir / MARKER_FILENAME
    existing_marker_path: Path | None = None

    prior_config = read_json(root_state_path, missing_ok=True)
    if devcontainer_dir.exists():
        if not devcontainer_dir.is_dir():
            raise ValueError(f"{devcontainer_dir} exists but is not a directory")
        existing_marker_path = find_marker_path(devcontainer_dir)
        if existing_marker_path is None:
            raise ValueError(
                f"{devcontainer_dir} exists but was not generated by {TOOL_NAME}; refusing to modify it"
            )
        marker = read_json(existing_marker_path, missing_ok=False)
        validate_generated_devcontainer(devcontainer_dir, marker)
        marker_config = marker.get("config")
        if isinstance(marker_config, dict):
            prior_config = marker_config
        if template_changed_since_generation(marker, prior_config, workspace):
            if not prompt_change(
                "The devcontainer template has changed since the last run. "
                "Upgrade to the latest template?"
            ):
                print()
                print(f"Kept {devcontainer_dir} unchanged.")
                return 0
    else:
        devcontainer_dir.mkdir()

    current_host_ports = config_list(prior_config, "host_ports", DEFAULT_HOST_PORTS)
    current_masked_paths = config_masked_paths(prior_config)
    detected_masked_paths = detected_venv_masked_paths(workspace)
    detected_read_only_paths = detected_package_manager_read_only_paths(workspace)
    current_read_only_paths = config_read_only_paths(prior_config, workspace)
    current_gpu = config_gpu(prior_config)

    host_ports = prompt_host_ports(current_host_ports)
    masked_paths = prompt_masked_paths(current_masked_paths)
    read_only_paths = prompt_read_only_paths(current_read_only_paths)
    masked_scan_paths = promptable_masked_scan_paths(
        detected_masked_paths,
        read_only_paths,
    )
    masked_paths = prompt_new_detected_masked_paths(
        masked_paths,
        masked_scan_paths,
        config_masked_scan_paths(prior_config),
    )
    read_only_scan_paths = promptable_read_only_scan_paths(
        detected_read_only_paths,
        masked_paths,
    )
    read_only_paths = prompt_new_detected_read_only_paths(
        read_only_paths,
        read_only_scan_paths,
        config_read_only_scan_paths(prior_config),
    )
    validate_path_lists(masked_paths, read_only_paths)
    gpu = prompt_gpu(current_gpu)
    config = {
        "version": CONFIG_VERSION,
        "host_ports": host_ports,
        "masked_paths": masked_paths,
        MASKED_SCAN_PATHS_KEY: masked_scan_paths,
        "read_only_paths": read_only_paths,
        READ_ONLY_SCAN_PATHS_KEY: read_only_scan_paths,
        "gpu": gpu,
    }

    masked_file_paths = detect_masked_file_paths(workspace, masked_paths)
    generated_files = render_files(
        host_ports,
        masked_paths,
        read_only_paths,
        gpu,
        masked_file_paths,
    )
    for relative_path, content in generated_files.items():
        path = devcontainer_dir / relative_path
        path.write_text(content, encoding="utf-8")
        if relative_path == "init-firewall.sh":
            path.chmod(0o755)

    marker = build_marker(config, generated_files)
    write_json(marker_path, marker)
    if existing_marker_path is not None and existing_marker_path != marker_path:
        existing_marker_path.unlink()
    write_json(root_state_path, config)

    print()
    print(f"Updated {devcontainer_dir}")
    print(f"Remembered answers in {root_state_path}")
    print("Rebuild or recreate the dev container for changes to take effect.")
    return 0


def find_marker_path(devcontainer_dir: Path) -> Path | None:
    marker_path = devcontainer_dir / MARKER_FILENAME
    if marker_path.exists():
        return marker_path
    for filename in LEGACY_MARKER_FILENAMES:
        legacy_marker_path = devcontainer_dir / filename
        if legacy_marker_path.exists():
            return legacy_marker_path
    return None


def validate_generated_devcontainer(devcontainer_dir: Path, marker: dict[str, Any]) -> None:
    if marker.get("generated_by") != TOOL_NAME:
        raise ValueError(
            f"{devcontainer_dir} exists but was not generated by {TOOL_NAME}; refusing to modify it"
        )
    hashes = marker.get("managed_files")
    if not isinstance(hashes, dict):
        raise ValueError(f"{devcontainer_dir} marker is missing managed file hashes")

    managed_paths = list(dict.fromkeys([*MANAGED_FILES, *hashes.keys()]))
    for relative_path in managed_paths:
        expected_hash = hashes.get(relative_path)
        if not isinstance(expected_hash, str):
            raise ValueError(f"{devcontainer_dir} marker is missing {relative_path}")
        path = devcontainer_dir / relative_path
        if not path.exists():
            raise ValueError(f"{path} is missing; refusing to modify this devcontainer")
        actual_hash = sha256_text(path.read_text(encoding="utf-8"))
        if actual_hash != expected_hash:
            raise ValueError(
                f"{path} has been modified since generation; refusing to overwrite it"
            )


def render_files(
    host_ports: list[int],
    masked_paths: list[str],
    read_only_paths: list[str],
    gpu: dict[str, str],
    masked_file_paths: list[str] | None = None,
) -> dict[str, str]:
    devcontainer_json = render_devcontainer_json(
        host_ports,
        masked_paths,
        read_only_paths,
        gpu,
        masked_file_paths,
    )
    parse_rendered_devcontainer_json(devcontainer_json)
    return {
        "Dockerfile": render_template(DOCKERFILE_TEMPLATE_NAME),
        "devcontainer.json": devcontainer_json,
        "init-firewall.sh": render_template(FIREWALL_TEMPLATE_NAME),
        MASKED_FILE_PLACEHOLDER: "",
    }


def render_template(template_name: str, **context: Any) -> str:
    environment = Environment(
        loader=FileSystemLoader(TEMPLATE_DIRECTORY),
        autoescape=False,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    try:
        return environment.get_template(template_name).render(**context)
    except (OSError, TemplateError) as exc:
        raise ValueError(f"Could not render template {template_name}: {exc}") from exc


def build_marker(
    config: dict[str, Any],
    generated_files: dict[str, str],
) -> dict[str, Any]:
    return {
        "generated_by": TOOL_NAME,
        "version": CONFIG_VERSION,
        TEMPLATE_FINGERPRINT_KEY: template_fingerprint(),
        "config": config,
        "managed_files": {
            relative_path: sha256_text(content)
            for relative_path, content in generated_files.items()
        },
    }


def template_changed_since_generation(
    marker: dict[str, Any],
    config: dict[str, Any],
    workspace: Path,
) -> bool:
    saved_fingerprint = marker.get(TEMPLATE_FINGERPRINT_KEY)
    if isinstance(saved_fingerprint, str):
        return saved_fingerprint != template_fingerprint()

    # Markers from older releases predate the explicit fingerprint. Compare the
    # files they recorded with what the current templates produce from the same
    # answers, so upgrading the configurator remains backwards compatible.
    masked_paths = config_masked_paths(config)
    generated_files = render_files(
        config_list(config, "host_ports", DEFAULT_HOST_PORTS),
        masked_paths,
        config_read_only_paths(config),
        config_gpu(config),
        detect_masked_file_paths(workspace, masked_paths),
    )
    managed_files = marker.get("managed_files")
    if not isinstance(managed_files, dict):
        return True
    return any(
        managed_files.get(relative_path) != sha256_text(content)
        for relative_path, content in generated_files.items()
    )


def template_fingerprint() -> str:
    digest = hashlib.sha256()
    for template_name in TEMPLATE_NAMES:
        template_path = TEMPLATE_DIRECTORY / template_name
        try:
            template_content = template_path.read_bytes()
        except OSError as exc:
            raise ValueError(
                f"Could not read template {template_path}: {exc}"
            ) from exc
        digest.update(template_name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(template_content)
        digest.update(b"\0")
    return digest.hexdigest()


def build_devcontainer_json(
    host_ports: list[int],
    masked_paths: list[str],
    read_only_paths: list[str],
    gpu: dict[str, str],
    masked_file_paths: list[str] | None = None,
) -> dict[str, Any]:
    return parse_rendered_devcontainer_json(
        render_devcontainer_json(
            host_ports,
            masked_paths,
            read_only_paths,
            gpu,
            masked_file_paths,
        )
    )


def render_devcontainer_json(
    host_ports: list[int],
    masked_paths: list[str],
    read_only_paths: list[str],
    gpu: dict[str, str],
    masked_file_paths: list[str] | None = None,
) -> str:
    validate_path_lists(masked_paths, read_only_paths)
    normalized_masked_paths = normalize_workspace_paths(masked_paths, "Masked")
    normalized_read_only_paths = normalize_workspace_paths(
        read_only_paths,
        "Read-only",
    )
    masked_file_path_set = set(
        normalize_workspace_paths(masked_file_paths or [], "Masked file")
    )
    return render_template(
        DEVCONTAINER_TEMPLATE_NAME,
        git_read_only=".git" in normalized_read_only_paths,
        gpu=normalize_gpu(gpu),
        host_ports=format_ports(host_ports),
        masked_file_paths=masked_file_path_set,
        masked_file_placeholder=MASKED_FILE_PLACEHOLDER,
        masked_paths=normalized_masked_paths,
        read_only_paths=normalized_read_only_paths,
    )


def parse_rendered_devcontainer_json(content: str) -> dict[str, Any]:
    try:
        data = json.loads(content)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Template {DEVCONTAINER_TEMPLATE_NAME} rendered invalid JSON: {exc}"
        ) from exc
    if not isinstance(data, dict):
        raise ValueError(
            f"Template {DEVCONTAINER_TEMPLATE_NAME} must render a JSON object"
        )
    return data


def read_json(path: Path, *, missing_ok: bool = False) -> dict[str, Any]:
    if missing_ok and not path.exists():
        return {}
    if not path.exists():
        raise ValueError(f"{path} does not exist")
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json_text(data), encoding="utf-8")


def json_text(data: dict[str, Any]) -> str:
    return json.dumps(data, indent=2) + "\n"


def config_list(
    config: dict[str, Any], key: str, default: list[Any]
) -> list[Any]:
    value = config.get(key)
    if isinstance(value, list):
        return value
    return default[:]


def config_masked_paths(config: dict[str, Any]) -> list[str]:
    if "masked_paths" in config:
        return normalize_workspace_paths(
            config_list(config, "masked_paths", []), "Masked"
        )
    if "hidden_paths" in config:
        hidden_paths = normalize_workspace_paths(
            config_list(config, "hidden_paths", []), "Hidden"
        )
        default_read_only_paths = set(DEFAULT_READ_ONLY_PATHS)
        return [path for path in hidden_paths if path not in default_read_only_paths]
    return DEFAULT_MASKED_PATHS[:]


def config_masked_scan_paths(config: dict[str, Any]) -> list[str]:
    return normalize_workspace_paths(
        config_list(config, MASKED_SCAN_PATHS_KEY, []),
        "Masked scan",
    )


def config_read_only_paths(
    config: dict[str, Any],
    workspace: Path | None = None,
) -> list[str]:
    if "read_only_paths" in config:
        read_only_paths = normalize_workspace_paths(
            config_list(config, "read_only_paths", []), "Read-only"
        )
        if should_extend_default_read_only_paths(config, read_only_paths):
            return default_read_only_paths(workspace)
        return read_only_paths
    if "hidden_paths" in config:
        hidden_paths = normalize_workspace_paths(
            config_list(config, "hidden_paths", []), "Hidden"
        )
        return [
            path
            for path in DEFAULT_READ_ONLY_PATHS
            if path in hidden_paths
        ]
    return default_read_only_paths(workspace)


def config_read_only_scan_paths(config: dict[str, Any]) -> list[str]:
    return normalize_workspace_paths(
        config_list(config, READ_ONLY_SCAN_PATHS_KEY, []),
        "Read-only scan",
    )


def should_extend_default_read_only_paths(
    config: dict[str, Any],
    read_only_paths: list[str],
) -> bool:
    version = config.get("version")
    if isinstance(version, int) and version >= CONFIG_VERSION:
        return False
    return read_only_paths == DEFAULT_READ_ONLY_PATHS


def default_read_only_paths(workspace: Path | None = None) -> list[str]:
    return merge_workspace_paths(
        DEFAULT_READ_ONLY_PATHS,
        detected_package_manager_read_only_paths(workspace),
    )


def detected_venv_masked_paths(workspace: Path | None) -> list[str]:
    if workspace is None:
        return []

    paths: list[str] = []
    for root, dirs, _files in os.walk(workspace):
        root_path = Path(root)
        if VENV_DIRNAME in dirs:
            paths.append(
                (root_path / VENV_DIRNAME).relative_to(workspace).as_posix()
            )
        dirs[:] = scannable_workspace_directories(dirs)
    return paths


def detected_package_manager_read_only_paths(workspace: Path | None) -> list[str]:
    if workspace is None:
        return []

    paths: list[str] = []
    for root, dirs, files in os.walk(workspace):
        dirs[:] = scannable_workspace_directories(dirs)
        root_path = Path(root)
        for filename in sorted(files):
            if filename not in PACKAGE_MANAGER_LOCK_FILENAMES:
                continue
            paths.append((root_path / filename).relative_to(workspace).as_posix())
    return paths


def scannable_workspace_directories(directories: list[str]) -> list[str]:
    return sorted(
        directory
        for directory in directories
        if not directory.startswith(".")
        and directory not in WORKSPACE_SCAN_IGNORED_DIRS
    )


def promptable_masked_scan_paths(
    detected_paths: list[str],
    read_only_paths: list[Any],
) -> list[str]:
    read_only = set(normalize_workspace_paths(read_only_paths, "Read-only"))
    return [
        path
        for path in normalize_workspace_paths(detected_paths, "Detected masked")
        if path not in read_only
    ]


def promptable_read_only_scan_paths(
    detected_paths: list[str],
    masked_paths: list[Any],
) -> list[str]:
    masked = set(normalize_workspace_paths(masked_paths, "Masked"))
    return [
        path
        for path in normalize_workspace_paths(detected_paths, "Detected read-only")
        if path not in masked
    ]


def config_gpu(config: dict[str, Any]) -> dict[str, str]:
    value = config.get("gpu")
    if isinstance(value, dict):
        return normalize_gpu(value)
    return DEFAULT_GPU.copy()


def prompt_host_ports(current: list[Any]) -> list[int]:
    normalized_current = normalize_host_ports(current)
    if not prompt_change(
        "Change host TCP ports reachable from the container through "
        f"host.docker.internal? Current: {format_ports(normalized_current) or 'none'}"
    ):
        return normalized_current
    raw = edit_prompt_value(
        "Host TCP ports",
        format_editor_list(str(port) for port in normalized_current),
    )
    new_ports = parse_host_ports(raw) if raw.strip() else []
    print_prompt_result(
        "Host TCP ports",
        format_ports(normalized_current) or "none",
        format_ports(new_ports) or "none",
    )
    return new_ports


def prompt_masked_paths(current: list[Any]) -> list[str]:
    normalized_current = normalize_workspace_paths(current, "Masked")
    if not prompt_change(
        "Change workspace paths to mask from the container? "
        f"Current: {format_display_list(normalized_current)}"
    ):
        return normalized_current
    raw = edit_prompt_value(
        "Workspace paths to mask",
        format_editor_list(normalized_current),
    ).strip()
    if not raw:
        new_paths: list[str] = []
    elif raw.lower() in {"none", "no", "-"}:
        new_paths = []
    else:
        new_paths = normalize_workspace_paths(split_editor_list(raw), "Masked")
    print_prompt_result(
        "Workspace paths to mask",
        format_display_list(normalized_current),
        format_display_list(new_paths),
    )
    return new_paths


def prompt_read_only_paths(current: list[Any]) -> list[str]:
    normalized_current = normalize_workspace_paths(current, "Read-only")
    if not prompt_change(
        "Change workspace paths to mount read-only in the container? "
        f"Current: {format_display_list(normalized_current)}"
    ):
        return normalized_current
    raw = edit_prompt_value(
        "Workspace paths to mount read-only",
        format_editor_list(normalized_current),
    ).strip()
    if not raw:
        new_paths = []
    elif raw.lower() in {"none", "no", "-"}:
        new_paths = []
    else:
        new_paths = normalize_workspace_paths(split_editor_list(raw), "Read-only")
    print_prompt_result(
        "Workspace paths to mount read-only",
        format_display_list(normalized_current),
        format_display_list(new_paths),
    )
    return new_paths


def prompt_new_detected_masked_paths(
    current: list[Any],
    detected_paths: list[Any],
    known_scan_paths: list[Any],
) -> list[str]:
    normalized_current = normalize_workspace_paths(current, "Masked")
    current_set = set(normalized_current)
    known_scan_set = set(normalize_workspace_paths(known_scan_paths, "Masked scan"))
    new_paths = [
        path
        for path in normalize_workspace_paths(detected_paths, "Detected masked")
        if path not in current_set and path not in known_scan_set
    ]
    if not new_paths:
        return normalized_current

    if not prompt_change(
        "Mask newly detected .venv directories from the container? "
        f"Found: {format_display_list(new_paths)}"
    ):
        return normalized_current

    raw = edit_prompt_value(
        "Newly detected .venv directories",
        format_editor_list(new_paths),
    ).strip()
    if not raw:
        selected_paths: list[str] = []
    elif raw.lower() in {"none", "no", "-"}:
        selected_paths = []
    else:
        selected_paths = normalize_workspace_paths(split_editor_list(raw), "Masked")

    selected_new_paths = [path for path in selected_paths if path not in current_set]
    if not selected_new_paths:
        print("Workspace paths to mask: nothing changed.")
        return normalized_current

    merged_paths = merge_workspace_paths(normalized_current, selected_new_paths)
    print(
        "Workspace paths to mask: added "
        f"{format_display_list(selected_new_paths)}."
    )
    return merged_paths


def prompt_new_detected_read_only_paths(
    current: list[Any],
    detected_paths: list[Any],
    known_scan_paths: list[Any],
) -> list[str]:
    normalized_current = normalize_workspace_paths(current, "Read-only")
    current_set = set(normalized_current)
    known_scan_set = set(normalize_workspace_paths(known_scan_paths, "Read-only scan"))
    new_paths = [
        path
        for path in normalize_workspace_paths(detected_paths, "Detected read-only")
        if path not in current_set and path not in known_scan_set
    ]
    if not new_paths:
        return normalized_current

    if not prompt_change(
        "Add newly detected lockfiles to the read-only mounts? "
        f"Found: {format_display_list(new_paths)}"
    ):
        return normalized_current

    raw = edit_prompt_value(
        "Newly detected read-only paths",
        format_editor_list(new_paths),
    ).strip()
    if not raw:
        selected_paths: list[str] = []
    elif raw.lower() in {"none", "no", "-"}:
        selected_paths = []
    else:
        selected_paths = normalize_workspace_paths(split_editor_list(raw), "Read-only")

    selected_new_paths = [path for path in selected_paths if path not in current_set]
    if not selected_new_paths:
        print("Workspace paths to mount read-only: nothing changed.")
        return normalized_current

    merged_paths = merge_workspace_paths(normalized_current, selected_new_paths)
    print(
        "Workspace paths to mount read-only: added "
        f"{format_display_list(selected_new_paths)}."
    )
    return merged_paths


def prompt_gpu(current: dict[str, str]) -> dict[str, str]:
    current = normalize_gpu(current)
    if not prompt_change(
        "Change GPU access? "
        f"Current: {format_gpu(current)}"
    ):
        return current
    raw = edit_prompt_value(
        "GPU access",
        format_gpu(current) + "\n",
    ).strip()
    new_gpu = parse_gpu(raw) if raw else DEFAULT_GPU.copy()
    print_prompt_result(
        "GPU access",
        format_gpu(current),
        format_gpu(new_gpu),
    )
    return new_gpu


def prompt_change(question: str) -> bool:
    while True:
        raw = input(f"{question} [y/N]: ").strip().lower()
        if not raw:
            return False
        if raw in {"y", "yes"}:
            return True
        if raw in {"n", "no"}:
            return False
        print("Please answer yes or no.")


def print_prompt_result(label: str, old_value: str, new_value: str) -> None:
    if old_value == new_value:
        print(f"{label}: nothing changed.")
        return
    print(f"{label}: changed from {old_value} to {new_value}.")


def edit_prompt_value(label: str, initial_text: str) -> str:
    editor = editor_command()
    if editor is None:
        raise ValueError("No terminal editor found. Set VISUAL or EDITOR and rerun.")

    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            delete=False,
            prefix=f"{editor_filename_label(label)}-",
            suffix=".txt",
        ) as temp_file:
            temp_file.write(initial_text)
            temp_path = Path(temp_file.name)

        print(
            f"Opening editor for {label}. "
            "Save an empty file to clear the value."
        )
        result = subprocess.run([*editor, str(temp_path)], check=False)
        if result.returncode != 0:
            raise ValueError(
                f"Editor exited with status {result.returncode}; no changes were written"
            )
        return temp_path.read_text(encoding="utf-8")
    finally:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)


def editor_command() -> list[str] | None:
    for env_name in ("VISUAL", "EDITOR"):
        configured_editor = os.environ.get(env_name)
        if configured_editor:
            command = shlex.split(configured_editor)
            if command:
                return command
    for fallback in ("nano", "vi"):
        if shutil.which(fallback):
            return [fallback]
    return None


def editor_filename_label(label: str) -> str:
    filename = re.sub(r"[^A-Za-z0-9_.-]+", "-", label.strip().lower()).strip("-")
    return filename or "devcontainer-config"


def format_display_list(values: list[str]) -> str:
    return ", ".join(values) or "none"


def format_editor_list(values: Any) -> str:
    lines = [str(value) for value in values]
    return "\n".join(lines) + ("\n" if lines else "")


def split_editor_list(raw: str) -> list[str]:
    return [
        token
        for token in re.split(r"[\n,]+", raw)
        if token.strip()
    ]


def parse_host_ports(raw: str) -> list[int]:
    if raw.lower() in {"none", "no", "-"}:
        return []

    ports: list[int] = []
    for token in re.split(r"[\s,]+", raw):
        token = token.strip()
        if not token:
            continue
        if "-" in token:
            start_text, end_text = token.split("-", 1)
            start = parse_port(start_text)
            end = parse_port(end_text)
            if start > end:
                raise ValueError(f"Invalid port range {token!r}: start is after end")
            ports.extend(range(start, end + 1))
        else:
            ports.append(parse_port(token))
    return sorted(set(ports))


def parse_port(value: Any) -> int:
    try:
        port = int(str(value).strip())
    except ValueError as exc:
        raise ValueError(f"Invalid port {value!r}") from exc
    if port < 1 or port > 65535:
        raise ValueError(f"Port {port} is outside 1-65535")
    return port


def normalize_host_ports(values: list[Any]) -> list[int]:
    ports = [parse_port(value) for value in values]
    return sorted(set(ports))


def normalize_workspace_paths(values: list[Any], label: str) -> list[str]:
    normalized: list[str] = []
    seen: set[str] = set()
    for value in values:
        path = str(value).strip().replace("\\", "/")
        if not path:
            continue
        path = path.lstrip("/")
        while path.startswith("./"):
            path = path[2:]
        if not path or path == ".":
            raise ValueError(f"{label} paths must be inside the workspace")
        parts = Path(path).parts
        if ".." in parts:
            raise ValueError(f"{label} path {value!r} must not contain '..'")
        if "," in path:
            raise ValueError(f"{label} path {value!r} must not contain commas")
        if path not in seen:
            normalized.append(path)
            seen.add(path)
    return normalized


def merge_workspace_paths(*path_lists: list[str]) -> list[str]:
    merged: list[str] = []
    seen: set[str] = set()
    for paths in path_lists:
        for path in normalize_workspace_paths(paths, "Workspace"):
            if path not in seen:
                merged.append(path)
                seen.add(path)
    return merged


def validate_path_lists(masked_paths: list[Any], read_only_paths: list[Any]) -> None:
    masked = set(normalize_workspace_paths(masked_paths, "Masked"))
    read_only = set(normalize_workspace_paths(read_only_paths, "Read-only"))
    overlap = sorted(masked & read_only)
    if overlap:
        paths = ", ".join(overlap)
        raise ValueError(f"Paths cannot be both masked and read-only: {paths}")


def detect_masked_file_paths(workspace: Path, masked_paths: list[Any]) -> list[str]:
    file_paths: list[str] = []
    for path in normalize_workspace_paths(masked_paths, "Masked"):
        workspace_path = workspace / path
        if workspace_path.exists() and not workspace_path.is_dir():
            file_paths.append(path)
    return file_paths


def parse_gpu(raw: str) -> dict[str, str]:
    value = raw.strip().lower()
    if value in {"none", "no", "-"}:
        return {"mode": "none", "device": ""}
    if value in {"all", "*"}:
        return {"mode": "all", "device": ""}
    if value.startswith("device="):
        return normalize_gpu({"mode": "device", "device": value.removeprefix("device=")})
    if value.startswith("gpu="):
        return normalize_gpu({"mode": "device", "device": value.removeprefix("gpu=")})
    return normalize_gpu({"mode": "device", "device": raw})


def normalize_gpu(value: Any) -> dict[str, str]:
    if not isinstance(value, dict):
        return DEFAULT_GPU.copy()
    mode = str(value.get("mode", "none")).strip().lower()
    device = str(value.get("device", "")).strip()
    if mode not in GPU_MODES:
        raise ValueError(f"Invalid GPU mode {mode!r}")
    if mode == "device":
        if not re.fullmatch(r"\d+", device):
            raise ValueError("GPU device must be a non-negative device number")
        return {"mode": "device", "device": str(int(device))}
    return {"mode": mode, "device": ""}


def format_gpu(gpu: dict[str, str]) -> str:
    gpu = normalize_gpu(gpu)
    if gpu["mode"] == "device":
        return f"device={gpu['device']}"
    return gpu["mode"]


def format_ports(ports: list[int]) -> str:
    return ",".join(str(port) for port in normalize_host_ports(ports))


def sha256_text(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


if __name__ == "__main__":
    raise SystemExit(main())
