"""Interactive CLI for generating Codex/Claude Code dev containers."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any


TOOL_NAME = "codex-claude-devcontainer-configurator"
CONFIG_VERSION = 4
DEVCONTAINER_DIRNAME = ".devcontainer"
ROOT_STATE_FILENAME = ".devcontainer-configurator.json"
MARKER_FILENAME = ".managed-file-hashes.json"
LEGACY_MARKER_FILENAMES = [
    ".devcontainer-configurator-managed-file-hashes.json",
    ".codex-claude-devcontainer-configurator.json",
]
MANAGED_FILES = ["Dockerfile", "devcontainer.json", "init-firewall.sh"]
MASKED_FILE_PLACEHOLDER = ".empty-mask"

DEFAULT_MASKED_PATHS = [".jj", ".git"]
DEFAULT_READ_ONLY_PATHS = [".devcontainer"]
READ_ONLY_SCAN_PATHS_KEY = "read_only_scan_paths"
PACKAGE_MANAGER_READ_ONLY_FILENAMES = {
    "package.json",
    "package-lock.json",
    "yarn.lock",
    ".yarnrc.yml",
    "pyproject.toml",
    "uv.lock",
}
READ_ONLY_SCAN_IGNORED_DIRS = {
    ".devcontainer",
    ".git",
    ".hg",
    ".jj",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "build",
    "dist",
    "node_modules",
    "venv",
}
DEFAULT_HOST_PORTS: list[int] = []
HOST_PORTS_ENV = "DEVCONTAINER_HOST_PORTS"
HOST_GATEWAY_ARG = "--add-host=host.docker.internal:host-gateway"
DEFAULT_GPU = {"mode": "none", "device": ""}
GPU_MODES = {"none", "device", "all"}

DOCKERFILE_TEMPLATE = """\
# Generated by codex-claude-devcontainer-configurator.
FROM node:20

ARG TZ
ENV TZ="$TZ"

ARG CLAUDE_CODE_VERSION=latest
ARG CODEX_CLI_VERSION=latest
ARG YARN_VERSION=4

ENV COREPACK_HOME=/usr/local/share/corepack

RUN apt-get update && apt-get install -y --no-install-recommends \\
  less \\
  git \\
  procps \\
  sudo \\
  fzf \\
  zsh \\
  man-db \\
  unzip \\
  gnupg2 \\
  gh \\
  iptables \\
  ipset \\
  iproute2 \\
  dnsutils \\
  aggregate \\
  jq \\
  nano \\
  vim \\
  python3-pip \\
  python3-venv \\
  pipx \\
  bubblewrap \\
  postgresql-client \\
  && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN chmod u+s /usr/bin/bwrap

RUN corepack enable && \\
  corepack install --global "yarn@${YARN_VERSION}" && \\
  yarn --version

RUN mkdir -p /usr/local/share/npm-global && \\
  chown -R node:node /usr/local/share

ARG USERNAME=node

RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \\
  && mkdir /commandhistory \\
  && touch /commandhistory/.bash_history \\
  && chown -R $USERNAME /commandhistory

ENV DEVCONTAINER=true

RUN mkdir -p /workspace /home/node/.claude /home/node/.codex && \\
  chown -R node:node /workspace /home/node/.claude /home/node/.codex

WORKDIR /workspace

ARG GIT_DELTA_VERSION=0.18.2
RUN ARCH=$(dpkg --print-architecture) && \\
  wget "https://github.com/dandavison/delta/releases/download/${GIT_DELTA_VERSION}/git-delta_${GIT_DELTA_VERSION}_${ARCH}.deb" && \\
  sudo dpkg -i "git-delta_${GIT_DELTA_VERSION}_${ARCH}.deb" && \\
  rm "git-delta_${GIT_DELTA_VERSION}_${ARCH}.deb"

USER node

ENV PATH="/home/node/.local/bin:${PATH}"

ENV NPM_CONFIG_PREFIX=/usr/local/share/npm-global
ENV PATH=$PATH:/usr/local/share/npm-global/bin

RUN pipx install uv && \\
  uv --version

ENV SHELL=/bin/zsh
ENV EDITOR=nano
ENV VISUAL=nano

ARG ZSH_IN_DOCKER_VERSION=1.2.0
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v${ZSH_IN_DOCKER_VERSION}/zsh-in-docker.sh)" -- \\
  -p git \\
  -p fzf \\
  -a "source /usr/share/doc/fzf/examples/key-bindings.zsh" \\
  -a "source /usr/share/doc/fzf/examples/completion.zsh" \\
  -a "export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \\
  -x

RUN npm install -g @anthropic-ai/claude-code@${CLAUDE_CODE_VERSION}
RUN npm install -g @openai/codex@${CODEX_CLI_VERSION}

COPY init-firewall.sh /usr/local/bin/
USER root
RUN chmod +x /usr/local/bin/init-firewall.sh && \\
  echo "node ALL=(root) NOPASSWD: SETENV: /usr/local/bin/init-firewall.sh" > /etc/sudoers.d/node-firewall && \\
  chmod 0440 /etc/sudoers.d/node-firewall
USER node
"""

FIREWALL_TEMPLATE = """\
#!/bin/bash
# Generated by codex-claude-devcontainer-configurator.
set -euo pipefail
IFS=$'\\n\\t'

DOCKER_DNS_RULES=$(iptables-save -t nat | grep "127\\.0\\.0\\.11" || true)

iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
ipset destroy allowed-domains 2>/dev/null || true

if [ -n "$DOCKER_DNS_RULES" ]; then
    echo "Restoring Docker DNS rules..."
    iptables -t nat -N DOCKER_OUTPUT 2>/dev/null || true
    iptables -t nat -N DOCKER_POSTROUTING 2>/dev/null || true
    echo "$DOCKER_DNS_RULES" | xargs -L 1 iptables -t nat
else
    echo "No Docker DNS rules to restore"
fi

iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A INPUT -p udp --sport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --sport 22 -m state --state ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

ipset create allowed-domains hash:net

echo "Fetching GitHub IP ranges..."
gh_ranges=$(curl -s https://api.github.com/meta)
if [ -z "$gh_ranges" ]; then
    echo "ERROR: Failed to fetch GitHub IP ranges"
    exit 1
fi

if ! echo "$gh_ranges" | jq -e '.web and .api and .git' >/dev/null; then
    echo "ERROR: GitHub API response missing required fields"
    exit 1
fi

echo "Processing GitHub IPs..."
while read -r cidr; do
    if [[ ! "$cidr" =~ ^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}/[0-9]{1,2}$ ]]; then
        echo "ERROR: Invalid CIDR range from GitHub meta: $cidr"
        exit 1
    fi
    echo "Adding GitHub range $cidr"
    ipset add allowed-domains "$cidr"
done < <(echo "$gh_ranges" | jq -r '(.web + .api + .git)[]' | aggregate -q)

for domain in \\
    "registry.npmjs.org" \\
    "api.anthropic.com" \\
    "api.openai.com" \\
    "auth.openai.com" \\
    "chatgpt.com" \\
    "sentry.io" \\
    "statsig.com" \\
    "marketplace.visualstudio.com" \\
    "vscode.blob.core.windows.net" \\
    "update.code.visualstudio.com"; do
    echo "Resolving $domain..."
    ips=$(dig +noall +answer A "$domain" | awk '$4 == "A" {print $5}')
    if [ -z "$ips" ]; then
        echo "ERROR: Failed to resolve $domain"
        exit 1
    fi

    while read -r ip; do
        if [[ ! "$ip" =~ ^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$ ]]; then
            echo "ERROR: Invalid IP from DNS for $domain: $ip"
            exit 1
        fi
        echo "Adding $ip for $domain"
        ipset add allowed-domains "$ip"
    done < <(echo "$ips")
done

HOST_IP=$(getent ahostsv4 host.docker.internal | awk '{print $1; exit}')
if [ -z "$HOST_IP" ]; then
    HOST_IP=$(ip route | grep default | cut -d" " -f3)
fi
if [ -z "$HOST_IP" ]; then
    echo "ERROR: Failed to detect host gateway IP"
    exit 1
fi

echo "Host gateway detected as: $HOST_IP"

if [ -n "${DEVCONTAINER_HOST_PORTS:-}" ]; then
    for port in ${DEVCONTAINER_HOST_PORTS//,/ }; do
        if [[ ! "$port" =~ ^[0-9]+$ ]] || [ "$port" -lt 1 ] || [ "$port" -gt 65535 ]; then
            echo "ERROR: Invalid DEVCONTAINER_HOST_PORTS entry: $port"
            exit 1
        fi
        echo "Allowing host.docker.internal:$port"
        iptables -A OUTPUT -p tcp -d "$HOST_IP" --dport "$port" -j ACCEPT
    done
else
    echo "No host.docker.internal ports configured"
fi

iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m set --match-set allowed-domains dst -j ACCEPT
iptables -A OUTPUT -j REJECT --reject-with icmp-admin-prohibited

echo "Firewall configuration complete"
echo "Verifying firewall rules..."
if curl --connect-timeout 5 https://example.com >/dev/null 2>&1; then
    echo "ERROR: Firewall verification failed - was able to reach https://example.com"
    exit 1
else
    echo "Firewall verification passed - unable to reach https://example.com as expected"
fi

if ! curl --connect-timeout 5 https://api.github.com/zen >/dev/null 2>&1; then
    echo "ERROR: Firewall verification failed - unable to reach https://api.github.com"
    exit 1
else
    echo "Firewall verification passed - able to reach https://api.github.com as expected"
fi
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Codex/Claude Code .devcontainer directory."
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=Path.cwd(),
        help="Workspace where .devcontainer should be created. Defaults to the current directory.",
    )
    args = parser.parse_args(argv)

    try:
        return configure(args.workspace.resolve())
    except ValueError as exc:
        print(f"error: {exc}")
        return 1


def configure(workspace: Path) -> int:
    if not workspace.exists() or not workspace.is_dir():
        raise ValueError(f"{workspace} is not a directory")

    devcontainer_dir = workspace / DEVCONTAINER_DIRNAME
    root_state_path = workspace / ROOT_STATE_FILENAME
    marker_path = devcontainer_dir / MARKER_FILENAME
    existing_marker_path: Path | None = None

    prior_config = read_json(root_state_path, missing_ok=True)
    if devcontainer_dir.exists():
        if not devcontainer_dir.is_dir():
            raise ValueError(f"{devcontainer_dir} exists but is not a directory")
        existing_marker_path = find_marker_path(devcontainer_dir)
        if existing_marker_path is None:
            raise ValueError(
                f"{devcontainer_dir} exists but was not generated by {TOOL_NAME}; refusing to modify it"
            )
        marker = read_json(existing_marker_path, missing_ok=False)
        validate_generated_devcontainer(devcontainer_dir, marker)
        marker_config = marker.get("config")
        if isinstance(marker_config, dict):
            prior_config = marker_config
    else:
        devcontainer_dir.mkdir()

    current_host_ports = config_list(prior_config, "host_ports", DEFAULT_HOST_PORTS)
    current_masked_paths = config_masked_paths(prior_config)
    detected_read_only_paths = detected_package_manager_read_only_paths(workspace)
    current_read_only_paths = config_read_only_paths(prior_config, workspace)
    current_gpu = config_gpu(prior_config)

    host_ports = prompt_host_ports(current_host_ports)
    masked_paths = prompt_masked_paths(current_masked_paths)
    read_only_paths = prompt_read_only_paths(current_read_only_paths)
    read_only_scan_paths = promptable_read_only_scan_paths(
        detected_read_only_paths,
        masked_paths,
    )
    read_only_paths = prompt_new_detected_read_only_paths(
        read_only_paths,
        read_only_scan_paths,
        config_read_only_scan_paths(prior_config),
    )
    validate_path_lists(masked_paths, read_only_paths)
    gpu = prompt_gpu(current_gpu)
    config = {
        "version": CONFIG_VERSION,
        "host_ports": host_ports,
        "masked_paths": masked_paths,
        "read_only_paths": read_only_paths,
        READ_ONLY_SCAN_PATHS_KEY: read_only_scan_paths,
        "gpu": gpu,
    }

    masked_file_paths = detect_masked_file_paths(workspace, masked_paths)
    generated_files = render_files(
        host_ports,
        masked_paths,
        read_only_paths,
        gpu,
        masked_file_paths,
    )
    for relative_path, content in generated_files.items():
        path = devcontainer_dir / relative_path
        path.write_text(content, encoding="utf-8")
        if relative_path == "init-firewall.sh":
            path.chmod(0o755)

    marker = build_marker(config, generated_files)
    write_json(marker_path, marker)
    if existing_marker_path is not None and existing_marker_path != marker_path:
        existing_marker_path.unlink()
    write_json(root_state_path, config)

    print()
    print(f"Updated {devcontainer_dir}")
    print(f"Remembered answers in {root_state_path}")
    print("Rebuild or recreate the dev container for changes to take effect.")
    return 0


def find_marker_path(devcontainer_dir: Path) -> Path | None:
    marker_path = devcontainer_dir / MARKER_FILENAME
    if marker_path.exists():
        return marker_path
    for filename in LEGACY_MARKER_FILENAMES:
        legacy_marker_path = devcontainer_dir / filename
        if legacy_marker_path.exists():
            return legacy_marker_path
    return None


def validate_generated_devcontainer(devcontainer_dir: Path, marker: dict[str, Any]) -> None:
    if marker.get("generated_by") != TOOL_NAME:
        raise ValueError(
            f"{devcontainer_dir} exists but was not generated by {TOOL_NAME}; refusing to modify it"
        )
    hashes = marker.get("managed_files")
    if not isinstance(hashes, dict):
        raise ValueError(f"{devcontainer_dir} marker is missing managed file hashes")

    managed_paths = list(dict.fromkeys([*MANAGED_FILES, *hashes.keys()]))
    for relative_path in managed_paths:
        expected_hash = hashes.get(relative_path)
        if not isinstance(expected_hash, str):
            raise ValueError(f"{devcontainer_dir} marker is missing {relative_path}")
        path = devcontainer_dir / relative_path
        if not path.exists():
            raise ValueError(f"{path} is missing; refusing to modify this devcontainer")
        actual_hash = sha256_text(path.read_text(encoding="utf-8"))
        if actual_hash != expected_hash:
            raise ValueError(
                f"{path} has been modified since generation; refusing to overwrite it"
            )


def render_files(
    host_ports: list[int],
    masked_paths: list[str],
    read_only_paths: list[str],
    gpu: dict[str, str],
    masked_file_paths: list[str] | None = None,
) -> dict[str, str]:
    return {
        "Dockerfile": DOCKERFILE_TEMPLATE,
        "devcontainer.json": json_text(
            build_devcontainer_json(
                host_ports,
                masked_paths,
                read_only_paths,
                gpu,
                masked_file_paths,
            )
        ),
        "init-firewall.sh": FIREWALL_TEMPLATE,
        MASKED_FILE_PLACEHOLDER: "",
    }


def build_marker(config: dict[str, Any], generated_files: dict[str, str]) -> dict[str, Any]:
    return {
        "generated_by": TOOL_NAME,
        "version": CONFIG_VERSION,
        "config": config,
        "managed_files": {
            relative_path: sha256_text(content)
            for relative_path, content in generated_files.items()
        },
    }


def build_devcontainer_json(
    host_ports: list[int],
    masked_paths: list[str],
    read_only_paths: list[str],
    gpu: dict[str, str],
    masked_file_paths: list[str] | None = None,
) -> dict[str, Any]:
    validate_path_lists(masked_paths, read_only_paths)
    normalized_masked_paths = normalize_workspace_paths(masked_paths, "Masked")
    normalized_read_only_paths = normalize_workspace_paths(read_only_paths, "Read-only")
    masked_file_path_set = set(
        normalize_workspace_paths(masked_file_paths or [], "Masked file")
    )
    container_env = {
        "NODE_OPTIONS": "--max-old-space-size=4096",
        "CLAUDE_CONFIG_DIR": "/home/node/.claude",
        "CODEX_HOME": "/home/node/.codex",
        "POWERLEVEL9K_DISABLE_GITSTATUS": "true",
        HOST_PORTS_ENV: format_ports(host_ports),
    }
    if ".git" in normalized_read_only_paths:
        container_env["GIT_OPTIONAL_LOCKS"] = "0"

    run_args: list[str] = [
        "--cap-add=SYS_ADMIN",
        "--cap-add=SYS_CHROOT",
        "--cap-add=SETUID",
        "--cap-add=SETGID",
        "--cap-add=SYS_PTRACE",
        "--security-opt=seccomp=unconfined",
        "--security-opt=apparmor=unconfined",
        "--cap-add=NET_ADMIN",
        "--cap-add=NET_RAW",
        HOST_GATEWAY_ARG,
    ]
    run_args = update_gpu_run_args(run_args, gpu)

    return {
        "name": "Claude Code/Codex Sandbox",
        "build": {
            "dockerfile": "Dockerfile",
            "context": ".",
            "args": {
                "TZ": "${localEnv:TZ:America/New_York}",
                "CLAUDE_CODE_VERSION": "latest",
                "CODEX_CLI_VERSION": "latest",
                "YARN_VERSION": "4",
                "GIT_DELTA_VERSION": "0.18.2",
                "ZSH_IN_DOCKER_VERSION": "1.2.0",
            },
        },
        "runArgs": run_args,
        "customizations": {
            "vscode": {
                "extensions": [
                    "anthropic.claude-code",
                    "dbaeumer.vscode-eslint",
                    "esbenp.prettier-vscode",
                    "eamodio.gitlens",
                ],
                "settings": {
                    "editor.formatOnSave": True,
                    "editor.defaultFormatter": "esbenp.prettier-vscode",
                    "editor.codeActionsOnSave": {
                        "source.fixAll.eslint": "explicit",
                    },
                    "terminal.integrated.defaultProfile.linux": "zsh",
                    "terminal.integrated.profiles.linux": {
                        "bash": {
                            "path": "bash",
                            "icon": "terminal-bash",
                        },
                        "zsh": {
                            "path": "zsh",
                        },
                    },
                },
            },
        },
        "remoteUser": "node",
        "mounts": [
            "source=claude-code-bashhistory-${devcontainerId},target=/commandhistory,type=volume",
            "source=claude-code-config-${devcontainerId},target=/home/node/.claude,type=volume",
            "source=codex-config-${devcontainerId},target=/home/node/.codex,type=volume",
            *[
                masked_mount(path, is_file=path in masked_file_path_set)
                for path in normalized_masked_paths
            ],
            *[read_only_mount(path) for path in normalized_read_only_paths],
        ],
        "containerEnv": container_env,
        "workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind,consistency=delegated",
        "workspaceFolder": "/workspace",
        "postStartCommand": (
            f'sudo {HOST_PORTS_ENV}="${{{HOST_PORTS_ENV}:-}}" '
            "/usr/local/bin/init-firewall.sh"
        ),
        "waitFor": "postStartCommand",
    }


def read_json(path: Path, *, missing_ok: bool = False) -> dict[str, Any]:
    if missing_ok and not path.exists():
        return {}
    if not path.exists():
        raise ValueError(f"{path} does not exist")
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json_text(data), encoding="utf-8")


def json_text(data: dict[str, Any]) -> str:
    return json.dumps(data, indent=2) + "\n"


def config_list(
    config: dict[str, Any], key: str, default: list[Any]
) -> list[Any]:
    value = config.get(key)
    if isinstance(value, list):
        return value
    return default[:]


def config_masked_paths(config: dict[str, Any]) -> list[str]:
    if "masked_paths" in config:
        return normalize_workspace_paths(
            config_list(config, "masked_paths", []), "Masked"
        )
    if "hidden_paths" in config:
        hidden_paths = normalize_workspace_paths(
            config_list(config, "hidden_paths", []), "Hidden"
        )
        default_read_only_paths = set(DEFAULT_READ_ONLY_PATHS)
        return [path for path in hidden_paths if path not in default_read_only_paths]
    return DEFAULT_MASKED_PATHS[:]


def config_read_only_paths(
    config: dict[str, Any],
    workspace: Path | None = None,
) -> list[str]:
    if "read_only_paths" in config:
        read_only_paths = normalize_workspace_paths(
            config_list(config, "read_only_paths", []), "Read-only"
        )
        if should_extend_default_read_only_paths(config, read_only_paths):
            return default_read_only_paths(workspace)
        return read_only_paths
    if "hidden_paths" in config:
        hidden_paths = normalize_workspace_paths(
            config_list(config, "hidden_paths", []), "Hidden"
        )
        return [
            path
            for path in DEFAULT_READ_ONLY_PATHS
            if path in hidden_paths
        ]
    return default_read_only_paths(workspace)


def config_read_only_scan_paths(config: dict[str, Any]) -> list[str]:
    return normalize_workspace_paths(
        config_list(config, READ_ONLY_SCAN_PATHS_KEY, []),
        "Read-only scan",
    )


def should_extend_default_read_only_paths(
    config: dict[str, Any],
    read_only_paths: list[str],
) -> bool:
    version = config.get("version")
    if isinstance(version, int) and version >= CONFIG_VERSION:
        return False
    return read_only_paths == DEFAULT_READ_ONLY_PATHS


def default_read_only_paths(workspace: Path | None = None) -> list[str]:
    return merge_workspace_paths(
        DEFAULT_READ_ONLY_PATHS,
        detected_package_manager_read_only_paths(workspace),
    )


def detected_package_manager_read_only_paths(workspace: Path | None) -> list[str]:
    if workspace is None:
        return []

    paths: list[str] = []
    for root, dirs, files in os.walk(workspace):
        dirs[:] = sorted(
            directory
            for directory in dirs
            if directory not in READ_ONLY_SCAN_IGNORED_DIRS
        )
        root_path = Path(root)
        for filename in sorted(files):
            if filename not in PACKAGE_MANAGER_READ_ONLY_FILENAMES:
                continue
            paths.append((root_path / filename).relative_to(workspace).as_posix())
    return paths


def promptable_read_only_scan_paths(
    detected_paths: list[str],
    masked_paths: list[Any],
) -> list[str]:
    masked = set(normalize_workspace_paths(masked_paths, "Masked"))
    return [
        path
        for path in normalize_workspace_paths(detected_paths, "Detected read-only")
        if path not in masked
    ]


def config_gpu(config: dict[str, Any]) -> dict[str, str]:
    value = config.get("gpu")
    if isinstance(value, dict):
        return normalize_gpu(value)
    return DEFAULT_GPU.copy()


def prompt_host_ports(current: list[Any]) -> list[int]:
    normalized_current = normalize_host_ports(current)
    if not prompt_change(
        "Change host TCP ports reachable from the container through "
        f"host.docker.internal? Current: {format_ports(normalized_current) or 'none'}"
    ):
        return normalized_current
    raw = edit_prompt_value(
        "Host TCP ports",
        format_editor_list(str(port) for port in normalized_current),
    )
    new_ports = parse_host_ports(raw) if raw.strip() else []
    print_prompt_result(
        "Host TCP ports",
        format_ports(normalized_current) or "none",
        format_ports(new_ports) or "none",
    )
    return new_ports


def prompt_masked_paths(current: list[Any]) -> list[str]:
    normalized_current = normalize_workspace_paths(current, "Masked")
    if not prompt_change(
        "Change workspace paths to mask from the container? "
        f"Current: {format_display_list(normalized_current)}"
    ):
        return normalized_current
    raw = edit_prompt_value(
        "Workspace paths to mask",
        format_editor_list(normalized_current),
    ).strip()
    if not raw:
        new_paths: list[str] = []
    elif raw.lower() in {"none", "no", "-"}:
        new_paths = []
    else:
        new_paths = normalize_workspace_paths(split_editor_list(raw), "Masked")
    print_prompt_result(
        "Workspace paths to mask",
        format_display_list(normalized_current),
        format_display_list(new_paths),
    )
    return new_paths


def prompt_read_only_paths(current: list[Any]) -> list[str]:
    normalized_current = normalize_workspace_paths(current, "Read-only")
    if not prompt_change(
        "Change workspace paths to mount read-only in the container? "
        f"Current: {format_display_list(normalized_current)}"
    ):
        return normalized_current
    raw = edit_prompt_value(
        "Workspace paths to mount read-only",
        format_editor_list(normalized_current),
    ).strip()
    if not raw:
        new_paths = []
    elif raw.lower() in {"none", "no", "-"}:
        new_paths = []
    else:
        new_paths = normalize_workspace_paths(split_editor_list(raw), "Read-only")
    print_prompt_result(
        "Workspace paths to mount read-only",
        format_display_list(normalized_current),
        format_display_list(new_paths),
    )
    return new_paths


def prompt_new_detected_read_only_paths(
    current: list[Any],
    detected_paths: list[Any],
    known_scan_paths: list[Any],
) -> list[str]:
    normalized_current = normalize_workspace_paths(current, "Read-only")
    current_set = set(normalized_current)
    known_scan_set = set(normalize_workspace_paths(known_scan_paths, "Read-only scan"))
    new_paths = [
        path
        for path in normalize_workspace_paths(detected_paths, "Detected read-only")
        if path not in current_set and path not in known_scan_set
    ]
    if not new_paths:
        return normalized_current

    if not prompt_change(
        "Add newly detected manifest/lock files to the read-only mounts? "
        f"Found: {format_display_list(new_paths)}"
    ):
        return normalized_current

    raw = edit_prompt_value(
        "Newly detected read-only paths",
        format_editor_list(new_paths),
    ).strip()
    if not raw:
        selected_paths: list[str] = []
    elif raw.lower() in {"none", "no", "-"}:
        selected_paths = []
    else:
        selected_paths = normalize_workspace_paths(split_editor_list(raw), "Read-only")

    selected_new_paths = [path for path in selected_paths if path not in current_set]
    if not selected_new_paths:
        print("Workspace paths to mount read-only: nothing changed.")
        return normalized_current

    merged_paths = merge_workspace_paths(normalized_current, selected_new_paths)
    print(
        "Workspace paths to mount read-only: added "
        f"{format_display_list(selected_new_paths)}."
    )
    return merged_paths


def prompt_gpu(current: dict[str, str]) -> dict[str, str]:
    current = normalize_gpu(current)
    if not prompt_change(
        "Change GPU access? "
        f"Current: {format_gpu(current)}"
    ):
        return current
    raw = edit_prompt_value(
        "GPU access",
        format_gpu(current) + "\n",
    ).strip()
    new_gpu = parse_gpu(raw) if raw else DEFAULT_GPU.copy()
    print_prompt_result(
        "GPU access",
        format_gpu(current),
        format_gpu(new_gpu),
    )
    return new_gpu


def prompt_change(question: str) -> bool:
    while True:
        raw = input(f"{question} [y/N]: ").strip().lower()
        if not raw:
            return False
        if raw in {"y", "yes"}:
            return True
        if raw in {"n", "no"}:
            return False
        print("Please answer yes or no.")


def print_prompt_result(label: str, old_value: str, new_value: str) -> None:
    if old_value == new_value:
        print(f"{label}: nothing changed.")
        return
    print(f"{label}: changed from {old_value} to {new_value}.")


def edit_prompt_value(label: str, initial_text: str) -> str:
    editor = editor_command()
    if editor is None:
        raise ValueError("No terminal editor found. Set VISUAL or EDITOR and rerun.")

    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            delete=False,
            prefix=f"{editor_filename_label(label)}-",
            suffix=".txt",
        ) as temp_file:
            temp_file.write(initial_text)
            temp_path = Path(temp_file.name)

        print(
            f"Opening editor for {label}. "
            "Save an empty file to clear the value."
        )
        result = subprocess.run([*editor, str(temp_path)], check=False)
        if result.returncode != 0:
            raise ValueError(
                f"Editor exited with status {result.returncode}; no changes were written"
            )
        return temp_path.read_text(encoding="utf-8")
    finally:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)


def editor_command() -> list[str] | None:
    for env_name in ("VISUAL", "EDITOR"):
        configured_editor = os.environ.get(env_name)
        if configured_editor:
            command = shlex.split(configured_editor)
            if command:
                return command
    for fallback in ("nano", "vi"):
        if shutil.which(fallback):
            return [fallback]
    return None


def editor_filename_label(label: str) -> str:
    filename = re.sub(r"[^A-Za-z0-9_.-]+", "-", label.strip().lower()).strip("-")
    return filename or "devcontainer-config"


def format_display_list(values: list[str]) -> str:
    return ", ".join(values) or "none"


def format_editor_list(values: Any) -> str:
    lines = [str(value) for value in values]
    return "\n".join(lines) + ("\n" if lines else "")


def split_editor_list(raw: str) -> list[str]:
    return [
        token
        for token in re.split(r"[\n,]+", raw)
        if token.strip()
    ]


def parse_host_ports(raw: str) -> list[int]:
    if raw.lower() in {"none", "no", "-"}:
        return []

    ports: list[int] = []
    for token in re.split(r"[\s,]+", raw):
        token = token.strip()
        if not token:
            continue
        if "-" in token:
            start_text, end_text = token.split("-", 1)
            start = parse_port(start_text)
            end = parse_port(end_text)
            if start > end:
                raise ValueError(f"Invalid port range {token!r}: start is after end")
            ports.extend(range(start, end + 1))
        else:
            ports.append(parse_port(token))
    return sorted(set(ports))


def parse_port(value: Any) -> int:
    try:
        port = int(str(value).strip())
    except ValueError as exc:
        raise ValueError(f"Invalid port {value!r}") from exc
    if port < 1 or port > 65535:
        raise ValueError(f"Port {port} is outside 1-65535")
    return port


def normalize_host_ports(values: list[Any]) -> list[int]:
    ports = [parse_port(value) for value in values]
    return sorted(set(ports))


def normalize_workspace_paths(values: list[Any], label: str) -> list[str]:
    normalized: list[str] = []
    seen: set[str] = set()
    for value in values:
        path = str(value).strip().replace("\\", "/")
        if not path:
            continue
        path = path.lstrip("/")
        while path.startswith("./"):
            path = path[2:]
        if not path or path == ".":
            raise ValueError(f"{label} paths must be inside the workspace")
        parts = Path(path).parts
        if ".." in parts:
            raise ValueError(f"{label} path {value!r} must not contain '..'")
        if "," in path:
            raise ValueError(f"{label} path {value!r} must not contain commas")
        if path not in seen:
            normalized.append(path)
            seen.add(path)
    return normalized


def merge_workspace_paths(*path_lists: list[str]) -> list[str]:
    merged: list[str] = []
    seen: set[str] = set()
    for paths in path_lists:
        for path in normalize_workspace_paths(paths, "Workspace"):
            if path not in seen:
                merged.append(path)
                seen.add(path)
    return merged


def validate_path_lists(masked_paths: list[Any], read_only_paths: list[Any]) -> None:
    masked = set(normalize_workspace_paths(masked_paths, "Masked"))
    read_only = set(normalize_workspace_paths(read_only_paths, "Read-only"))
    overlap = sorted(masked & read_only)
    if overlap:
        paths = ", ".join(overlap)
        raise ValueError(f"Paths cannot be both masked and read-only: {paths}")


def detect_masked_file_paths(workspace: Path, masked_paths: list[Any]) -> list[str]:
    file_paths: list[str] = []
    for path in normalize_workspace_paths(masked_paths, "Masked"):
        workspace_path = workspace / path
        if workspace_path.exists() and not workspace_path.is_dir():
            file_paths.append(path)
    return file_paths


def parse_gpu(raw: str) -> dict[str, str]:
    value = raw.strip().lower()
    if value in {"none", "no", "-"}:
        return {"mode": "none", "device": ""}
    if value in {"all", "*"}:
        return {"mode": "all", "device": ""}
    if value.startswith("device="):
        return normalize_gpu({"mode": "device", "device": value.removeprefix("device=")})
    if value.startswith("gpu="):
        return normalize_gpu({"mode": "device", "device": value.removeprefix("gpu=")})
    return normalize_gpu({"mode": "device", "device": raw})


def normalize_gpu(value: Any) -> dict[str, str]:
    if not isinstance(value, dict):
        return DEFAULT_GPU.copy()
    mode = str(value.get("mode", "none")).strip().lower()
    device = str(value.get("device", "")).strip()
    if mode not in GPU_MODES:
        raise ValueError(f"Invalid GPU mode {mode!r}")
    if mode == "device":
        if not re.fullmatch(r"\d+", device):
            raise ValueError("GPU device must be a non-negative device number")
        return {"mode": "device", "device": str(int(device))}
    return {"mode": mode, "device": ""}


def format_gpu(gpu: dict[str, str]) -> str:
    gpu = normalize_gpu(gpu)
    if gpu["mode"] == "device":
        return f"device={gpu['device']}"
    return gpu["mode"]


def update_gpu_run_args(run_args: list[str], gpu: dict[str, str]) -> list[str]:
    normalized_gpu = normalize_gpu(gpu)
    retained_args: list[str] = []
    skip_next = False
    for arg in run_args:
        if skip_next:
            skip_next = False
            continue
        if arg == "--gpus":
            skip_next = True
            continue
        if isinstance(arg, str) and arg.startswith("--gpus="):
            continue
        retained_args.append(arg)

    if normalized_gpu["mode"] == "all":
        retained_args.append("--gpus=all")
    elif normalized_gpu["mode"] == "device":
        retained_args.append(f"--gpus=device={normalized_gpu['device']}")
    return retained_args


def format_ports(ports: list[int]) -> str:
    return ",".join(str(port) for port in normalize_host_ports(ports))


def masked_mount(path: str, *, is_file: bool = False) -> str:
    if is_file:
        return (
            f"source=${{localWorkspaceFolder}}/.devcontainer/{MASKED_FILE_PLACEHOLDER},"
            f"target=/workspace/{path},type=bind,readonly"
        )
    return f"target=/workspace/{path},type=volume,volume-nocopy"


def read_only_mount(path: str) -> str:
    return (
        f"source=${{localWorkspaceFolder}}/{path},"
        f"target=/workspace/{path},type=bind,readonly"
    )


def sha256_text(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


if __name__ == "__main__":
    raise SystemExit(main())
